# Generated by Django 4.1.2 on 2022-10-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_image', models.ImageField(default='', null=True, upload_to='')),
                ('user_password', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
    ]
