# Generated by Django 4.1.2 on 2022-10-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0003_restaurant_rest_short_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_food_category',
            name='food_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
