# Generated by Django 4.1.2 on 2022-10-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Food_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=50)),
                ('rest_location', models.CharField(max_length=100)),
                ('rest_description', models.TextField()),
                ('rest_is_in_top_twenty', models.BooleanField(default=False)),
                ('price_category', models.CharField(choices=[('Lower', 'Lower'), ('Medium', 'Medium'), ('Higher', 'Higher')], max_length=60)),
                ('contact_no', models.CharField(max_length=50)),
                ('rest_main_img', models.ImageField(default='', upload_to='')),
                ('rest_pic1', models.ImageField(default='', upload_to='')),
                ('rest_pic2', models.ImageField(default='', upload_to='')),
                ('rest_pic3', models.ImageField(default='', upload_to='')),
                ('special_food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Src_App.restaurant_food_category')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=50)),
                ('chef_desc', models.TextField()),
                ('chef_ranking', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=30)),
                ('chef_img', models.ImageField(default='', upload_to='')),
                ('related_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Src_App.restaurant')),
            ],
        ),
    ]
