# Generated by Django 4.1.2 on 2022-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_short_intro',
            field=models.CharField(default='Enter your description here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_category',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=60),
        ),
    ]
