# Generated by Django 4.1.2 on 2022-10-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
